version: "3.4"

services: 
    mt-client:
        container_name: client
        ports: 
            - 3000:3000
        build: 
            context: 'client'
            dockerfile: Dockerfile
        volumes: 
            - './client:/app'
    mt-database:
        build:
            context: ./server/docker/database
            dockerfile: Dockerfile
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./server/docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./server/docker/database/data:/var/lib/mysql
    mt-php:
        restart: always
        build:
            context: ./server/docker/php-fpm
        depends_on:
            - mt-database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
        volumes:
            - ./server/symfony:/var/www
    mt-nginx:
        restart: always
        build:
            context: ./server/docker/nginx
        volumes:
            - ./server/symfony:/var/www
            - ./server/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./server/docker/nginx/sites/:/etc/nginx/sites-available
            - ./server/docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./server/docker/logs:/var/log
        depends_on:
            - mt-php
        ports:
            - "80:80"